### ISSUE TITLE
How does the plugin work?

### ISSUE THREAD

**Issue by mdufaisal** [ccin2p3/nagios-plugin-sssd-backend-status#2]
I tried to implement it inside nagios.
I defined a check command, and defined a service using the command.
But I am getting the following error on nagios GUI:

**return code of 13 for service 'sssd_backend_status' on host 'server1' was out of bounds**
Can someone pls help?
Does this plugin still work? Or Am I doing something wrong?
It works fine when used in Command line.

**Comment by riton** [comment]
Hi @isFaisalEqualsTrue . Yes this plugin definitely works and we're still using it in production.

Can you provide more context about your configuration ?

> I defined a check command, and defined a service using the command.

What are the definitions ?

How is the plugin executed ? remotely ? Running as which user ?

Please provide all the details you have. Without that we'll be unable to help you.

**Comment by mdufaisal** [comment]
Hi thanks so much for responding!

I am trying to execute the plugin remotely from an nms server as nagios user.

**Comment by riton** [comment]
> I am trying to execute the plugin remotely from an nms server as nagios user.

Have you authorized the _nagios user_ to query the `sssd-ifp` backend ?

As seen in the `sssd-ifp(5)` man page, the `allowed_uids` parameter can be used to specify a comma-separated list of UID values or user names that are allowed to access the InfoPipe responder.

Another solution is to use `sudo` to execute the plugin as `root`.

**Comment by riton** [comment]
A note has been added in the `README` file

**Comment by mdufaisal** [comment]
Executing the plugin as root kind of solved the issue.
Can this plugin be executed remotely? for remote hosts where sssd is running?

**Comment by riton** [comment]
> Can this plugin be executed remotely?

Yes, just like any other nagios plugin, through [`nrpe`](https://assets.nagios.com/downloads/nagioscore/docs/nrpe/NRPE.pdf) or equivalent command. https://exchange.nagios.org/directory/Addons/Monitoring-Agents is a good place to start looking.

**Comment by riton** [comment]
Closing as staled
